version: "3"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:19092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:19092

  rabbitMq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672

  frontend:
    build: ./LoanUi
    ports:
      - 8080:80

  bankservice-1:
    build: ./BankService
    environment:
      DOTNET_ENVIRONMENT: Service1
  
  bankservice-2:
    build: ./BankService
    environment:
      DOTNET_ENVIRONMENT: Service2
